version: "3.8"
services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "victor@datarisk.com"
      PGADMIN_DEFAULT_PASSWORD: "datarisk1234"
    ports:
      - 5050:80
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./docker_init.sql:/docker-entrypoint-initdb.d/docker_init.sql
      - ./base_info.csv:/var/lib/postgresql/data/pgadata/base_info.csv
      - ./base_pagamentos_desenvolvimento_clean.csv:/var/lib/postgresql/data/pgadata/base_pagamentos_desenvolvimento_clean.csv
      - ./base_cadastral.csv:/var/lib/postgresql/data/pgadata/base_cadastral.csv
  postgres_metabase:
    container_name: postgres_metabase
    image: postgres:14
    environment:
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase
      - POSTGRES_DB=metabase
  metabase:
    container_name: metabase
    depends_on:
      - postgres_metabase
    image: metabase/metabase:v0.43.4
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase
      - MB_DB_HOST=postgres_metabase
    ports:
      - 3000:3000